Feature/bookmarks
lavaloop-official/GovLearn-client pull request #20
Opened 2023-12-04 19:51 UTC by comlit

- added ability to bookmark courses and display them on a seperate page
- refactored auth state (auth token is no longer stored in redux - only authstate (t/f) is stored there)

2023-12-04 21:32 UTC, Mrjulss requested changes
Sehr nice schonmal, nur ein paar Kleinigkeiten
- Fände es cool wenn wir einfach das Standard-Icon für Bookmarks verwenden, dann kommt man nicht durcheinander (https://fontawesome.com/icons/bookmark?f=classic&s=solid) bei antdesign hab ich es leider nicht gefunden
- die Sterne auf der Markierte Kurse Seite werden nicht angezeigt, sollen dass Durchschnitssbewertungen sein oder eigene Bewertungen? Wird soweit ich das sehe beides nicht abgefragt

2023-12-04 21:35 UTC, Mrjulss commented on src/pages/Bookmarks.tsx
> +                <h1>Bookmarks</h1>
nicht verwaltungsdeutsch-tauglich ;P

2023-12-05 09:50 UTC, comlit commented
> Sehr nice schonmal, nur ein paar Kleinigkeiten
> - Fände es cool wenn wir einfach das Standard-Icon für Bookmarks verwenden, dann kommt man nicht durcheinander (https://fontawesome.com/icons/bookmark?f=classic&s=solid) bei antdesign hab ich es leider nicht gefunden
> - die Sterne auf der Markierte Kurse Seite werden nicht angezeigt, sollen dass Durchschnitssbewertungen sein oder eigene Bewertungen? Wird soweit ich das sehe beides nicht abgefragt

Jo anderes Icon macht auf jeden Fall Sinn. Hatte ich auch schon drüber nachgedacht. Ändere ich. Die compontents mit denen die markierten Kurse dargestellt werden hab ich einfach ganz frech von der Suche geklaut. Sollte aber die durchschnittliche Bewertung sein die da angezeigt wird. Man sollte auch vielleicht nochmal drüber nachdenken die direkt im Kurs mitzugeben. Sonst müsste man für jeden Kurs ja einen einzelnen request machen. Was ja bei der Suche zb echt ineffizient wäre

2023-12-05 19:49 UTC, Mrjulss approved these changes
Also die leeren Sterne ignorieren wir erstmal und schauen, dass wir die Durchschnittsbewertung in den Course Objekt reinkriegen?

2023-12-05 21:24 UTC, comlit commented
> Also die leeren Sterne ignorieren wir erstmal und schauen, dass wir die Durchschnittsbewertung in den Course Objekt reinkriegen?

Ja wenn man das mit rein bekommt wäre krass. Ist ja gerade auch noch das issue offen bezüglich was passieren soll wenn es noch keine Bewertungen gibt. Je nachdem was in dem Fall zurück kommt kann man die Sterne ja ausblenden dann.

2023-12-05 22:10 UTC, merged