fixed attributes
lavaloop-official/GovLearn-client pull request #27
Opened 2023-12-11 20:45 UTC by Mrjulss

2023-12-12 20:15 UTC, Paramian requested changes

2023-12-12 20:15 UTC, Paramian commented on src/pages/Details.tsx
> +                                                    <p className="attribute-value">{course.costFree ? 'vorhanden' : 'nicht vorhanden'}</p>
Du benutzt hier costFree anstatt Zertifikat :)

2023-12-14 22:13 UTC, comlit approved these changes
sieht gut aus👍

2023-12-19 16:04 UTC, Paramian approved these changes

2023-12-23 11:53 UTC, merged