Fix/UI enhancements
lavaloop-official/GovLearn-client pull request #29
Opened 2023-12-13 14:59 UTC by comlit

- footer is now always at the bottom 
- searchbar is finally centered lol
- outsourced some style tags for better readability
- made recommendations, search results and marked courses clickable

2023-12-14 20:56 UTC, Mrjulss requested changes
![image](https://github.com/lavaloop-official/GovLearn-client/assets/95315819/c0b60e2d-29b5-41c5-bfa4-56331572ed2a)
schonmal sehr nice, mir ist nur auf der Discover page aufgefallen, dass der Schatten so in dem Block verschwindet, was etwas komisch aussieht. Außerdem ist das Bild nicht ganz zentiert was die Auswahl bei Kursen nebeneinander komisch aussehen lässt

2023-12-14 21:03 UTC, comlit commented
> ![image](https://private-user-images.githubusercontent.com/95315819/290654487-c0b60e2d-29b5-41c5-bfa4-56331572ed2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1ODc5NzgsIm5iZiI6MTcwMjU4NzY3OCwicGF0aCI6Ii85NTMxNTgxOS8yOTA2NTQ0ODctYzBiNjBlMmQtMjliNS00MWM1LWJmYTQtNTYzMzE1NzJlZDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDIxMDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NzM2ZDZlYWI4MTk0NjdhZGJjZmY4Y2UwMmMwYzM2MTBiMDRjNGFmMzM0YTNmNmJlY2Q4MDZiZWZmY2I0OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hC3Dq9ImnqxGT6hZcbHYV_6lPjleGzFsKJyf4Il6Zcs) schonmal sehr nice, mir ist nur auf der Discover page aufgefallen, dass der Schatten so in dem Block verschwindet, was etwas komisch aussieht. Außerdem ist das Bild nicht ganz zentiert was die Auswahl bei Kursen nebeneinander komisch aussehen lässt

ja das liegt an dem komischen container wo die drinne sind. das ist so ein caroussel wo man so durchrotieren kann wenn da mehrere kurse drinne sind. das aber kacke das wollte ich sowieso noch austauschen

2023-12-16 21:02 UTC, comlit commented
hab das carousel jetzt nochmal komplett selbst implementiert. wir müssen die mock daten nochmal so abändern das man das auch sieht in den demos. das hat mir zu viel lebenszeit gekostet sonst

2023-12-23 11:25 UTC, Mrjulss approved these changes
sehr coole Arbeit mit dem Carousel

2023-12-23 11:54 UTC, merged