Feature/extend profil
lavaloop-official/GovLearn-client pull request #38
Opened 2024-01-01 15:45 UTC by Paramian

Change Mail
Change Name
Change Password
Extended helper to now output response to display propper error handling

2024-01-01 18:32 UTC, comlit commented
lass uns die profilseite dann doch direkt auch an das ui was wir auf den anderen seiten auch haben anpassen. dann ist das alles ein bisschen konsistenter. und man muss nicht noch mal drüber

2024-01-01 18:49 UTC, Paramian commented
@comlit gerne :) was fehlt dir noch?

2024-01-01 19:43 UTC, comlit requested changes
ich glaube es wäre gut wenn man den nutzer das neue passwort zweimal eingeben lässt. also das man es einfach zweimal untereinander schreibt. ist beim loginmodal bei der registrierung auf so implementiert kannst dir von da klauen

2024-01-03 12:15 UTC, Paramian commented
@comlit ist jetzt mit eingebaut :) gerne nochmal reviewen

2024-01-03 15:21 UTC, comlit approved these changes
top

2024-01-03 15:21 UTC, merged